// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.2
// source: swcat/plugin/v1/plugin.proto

package plugin_pb

import (
	pb "github.com/dnswlt/swcat/internal/catalog/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the plugin instance as defined in plugins.yml.
	PluginName string `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	// The entity that the plugin is executed for.
	Entity *pb.Entity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	// The configuration for the plugin (the spec.config section from plugins.yml).
	Config *structpb.Struct `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	// Additional dynamic arguments passed to the plugin execution.
	Args          *structpb.Struct `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_swcat_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_swcat_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *ExecuteRequest) GetEntity() *pb.Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *ExecuteRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecuteRequest) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

type GeneratedFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The relative path or filename of the generated file.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// The raw content of the file.
	Content       []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedFile) Reset() {
	*x = GeneratedFile{}
	mi := &file_swcat_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedFile) ProtoMessage() {}

func (x *GeneratedFile) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedFile.ProtoReflect.Descriptor instead.
func (*GeneratedFile) Descriptor() ([]byte, []int) {
	return file_swcat_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratedFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GeneratedFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Success indicates if the operation was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message - populated if success is false.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Files generated or extracted by the plugin.
	Files []*GeneratedFile `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	// Annotations to be added to the entity.
	Annotations   map[string]*structpb.Value `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_swcat_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_swcat_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetFiles() []*GeneratedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ExecuteResponse) GetAnnotations() map[string]*structpb.Value {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_swcat_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_swcat_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cswcat/plugin/v1/plugin.proto\x12\x0fswcat.plugin.v1\x1a\x1eswcat/catalog/v1/catalog.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc1\x01\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x120\n" +
	"\x06entity\x18\x02 \x01(\v2\x18.swcat.catalog.v1.EntityR\x06entity\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12+\n" +
	"\x04args\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04args\"=\n" +
	"\rGeneratedFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\xa4\x02\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x124\n" +
	"\x05files\x18\x03 \x03(\v2\x1e.swcat.plugin.v1.GeneratedFileR\x05files\x12S\n" +
	"\vannotations\x18\x04 \x03(\v21.swcat.plugin.v1.ExecuteResponse.AnnotationsEntryR\vannotations\x1aV\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x012_\n" +
	"\rPluginService\x12N\n" +
	"\aExecute\x12\x1f.swcat.plugin.v1.ExecuteRequest\x1a .swcat.plugin.v1.ExecuteResponse\"\x00B7Z5github.com/dnswlt/swcat/internal/plugins/pb;plugin_pbb\x06proto3"

var (
	file_swcat_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_swcat_plugin_v1_plugin_proto_rawDescData []byte
)

func file_swcat_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_swcat_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_swcat_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swcat_plugin_v1_plugin_proto_rawDesc), len(file_swcat_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_swcat_plugin_v1_plugin_proto_rawDescData
}

var file_swcat_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_swcat_plugin_v1_plugin_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: swcat.plugin.v1.ExecuteRequest
	(*GeneratedFile)(nil),   // 1: swcat.plugin.v1.GeneratedFile
	(*ExecuteResponse)(nil), // 2: swcat.plugin.v1.ExecuteResponse
	nil,                     // 3: swcat.plugin.v1.ExecuteResponse.AnnotationsEntry
	(*pb.Entity)(nil),       // 4: swcat.catalog.v1.Entity
	(*structpb.Struct)(nil), // 5: google.protobuf.Struct
	(*structpb.Value)(nil),  // 6: google.protobuf.Value
}
var file_swcat_plugin_v1_plugin_proto_depIdxs = []int32{
	4, // 0: swcat.plugin.v1.ExecuteRequest.entity:type_name -> swcat.catalog.v1.Entity
	5, // 1: swcat.plugin.v1.ExecuteRequest.config:type_name -> google.protobuf.Struct
	5, // 2: swcat.plugin.v1.ExecuteRequest.args:type_name -> google.protobuf.Struct
	1, // 3: swcat.plugin.v1.ExecuteResponse.files:type_name -> swcat.plugin.v1.GeneratedFile
	3, // 4: swcat.plugin.v1.ExecuteResponse.annotations:type_name -> swcat.plugin.v1.ExecuteResponse.AnnotationsEntry
	6, // 5: swcat.plugin.v1.ExecuteResponse.AnnotationsEntry.value:type_name -> google.protobuf.Value
	0, // 6: swcat.plugin.v1.PluginService.Execute:input_type -> swcat.plugin.v1.ExecuteRequest
	2, // 7: swcat.plugin.v1.PluginService.Execute:output_type -> swcat.plugin.v1.ExecuteResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_swcat_plugin_v1_plugin_proto_init() }
func file_swcat_plugin_v1_plugin_proto_init() {
	if File_swcat_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swcat_plugin_v1_plugin_proto_rawDesc), len(file_swcat_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swcat_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_swcat_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_swcat_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_swcat_plugin_v1_plugin_proto = out.File
	file_swcat_plugin_v1_plugin_proto_goTypes = nil
	file_swcat_plugin_v1_plugin_proto_depIdxs = nil
}
