apiVersion: swcat/v1alpha1
kind: System
metadata:
  name: cucumber-system
  title: Cucumber System
  description: |
    The Cucumber System does many wonderful things:

    * Download stuff
    * Process items
    * **New**: execute code: `3 < 4`.
  tags:
    - mission-critical
  links:
    - url: https://example.com/docs/cucumber
      title: Documentation
      type: docs
    - url: https://example.com/repo/cucumber
      title: Git repo
      type: repository
spec:
  owner: cucumber-team
  domain: plants-domain
  type: application
---
apiVersion: swcat/v1alpha1
kind: Component
metadata:
  name: cucumber-api-gateway
  title: Cucumber API Gateway
  tags: [public]
  labels:
    foobar.dev/language: java
    foobar.dev/deployment: k8s
spec:
  type: service
  lifecycle: production
  owner: cucumber-team
  system: cucumber-system
  providesApis:
    # You can add labels to references in two ways. As a ref/label struct:
    - ref: cucumber-api
      label: partial
  consumesApis:
    # Or as a "label" suffix
    - cucumber-backend-api "fwd"
---
apiVersion: swcat/v1alpha1
kind: Component
metadata:
  name: cucumber-backend
  title: Cucumber Backend
  labels:
    foobar.dev/language: java
    foobar.dev/deployment: k8s
spec:
  type: service
  lifecycle: production
  owner: cucumber-team
  system: cucumber-system
  providesApis:
    - cucumber-backend-api
  dependsOn:
    - resource:cucumber-db
---
apiVersion: swcat/v1alpha1
kind: Resource
metadata:
  name: cucumber-db
  title: Cucumber Database
  labels:
    foobar.dev/technology: postgres
spec:
  type: database
  owner: cucumber-team
  system: cucumber-system
---
apiVersion: swcat/v1alpha1
kind: API
metadata:
  name: cucumber-api
  title: Cucumber API
  links:
    - url: https://example.com/apis/cucumber-api
      title: Cucumber API Schema
      type: schema
spec:
  type: rest
  lifecycle: production
  owner: cucumber-team
  system: cucumber-system
---
apiVersion: swcat/v1alpha1
kind: API
metadata:
  name: cucumber-backend-api
  title: Cucumber Backend API
  links:
    - url: https://example.com/apis/cucumber-backend-api
      title: Cucumber Backend API Schema
      type: schema
spec:
  type: grpc
  lifecycle: production
  owner: cucumber-team
  system: cucumber-system
