// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.2
// source: swcat/catalog/v1/catalog.proto

package catalog_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DependencyRelation classifies the nature of an observed dependency.
type DependencyRelation int32

const (
	// Unknown relation; treated as a generic dependency.
	DependencyRelation_DEPENDENCY_RELATION_UNSPECIFIED DependencyRelation = 0
	// The source entity makes synchronous calls to the target, e.g. via REST,
	// gRPC or GraphQL.
	DependencyRelation_DEPENDENCY_RELATION_CALLS DependencyRelation = 1
	// The source entity produces messages/events to the target, e.g. a pub/sub
	// topic or message queue.
	DependencyRelation_DEPENDENCY_RELATION_PRODUCES DependencyRelation = 2
	// The source entity consumes messages/events from the target, e.g. as a
	// pub/sub subscriber or queue consumer.
	DependencyRelation_DEPENDENCY_RELATION_CONSUMES DependencyRelation = 3
)

// Enum value maps for DependencyRelation.
var (
	DependencyRelation_name = map[int32]string{
		0: "DEPENDENCY_RELATION_UNSPECIFIED",
		1: "DEPENDENCY_RELATION_CALLS",
		2: "DEPENDENCY_RELATION_PRODUCES",
		3: "DEPENDENCY_RELATION_CONSUMES",
	}
	DependencyRelation_value = map[string]int32{
		"DEPENDENCY_RELATION_UNSPECIFIED": 0,
		"DEPENDENCY_RELATION_CALLS":       1,
		"DEPENDENCY_RELATION_PRODUCES":    2,
		"DEPENDENCY_RELATION_CONSUMES":    3,
	}
)

func (x DependencyRelation) Enum() *DependencyRelation {
	p := new(DependencyRelation)
	*p = x
	return p
}

func (x DependencyRelation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyRelation) Descriptor() protoreflect.EnumDescriptor {
	return file_swcat_catalog_v1_catalog_proto_enumTypes[0].Descriptor()
}

func (DependencyRelation) Type() protoreflect.EnumType {
	return &file_swcat_catalog_v1_catalog_proto_enumTypes[0]
}

func (x DependencyRelation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyRelation.Descriptor instead.
func (DependencyRelation) EnumDescriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

// Metadata common to all entities.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the entity. Must be unique within the catalog at any given point in time, for any given namespace + kind pair.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The namespace that the entity belongs to. If empty, the entity is assume to live in the default namespace.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// A display name of the entity, to be presented in user interfaces instead of the name property, when available.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// A short (typically relatively few words, on one line) description of the entity.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Key/value pairs of identifying information attached to the entity.
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Key/value pairs of non-identifying auxiliary information attached to the entity.
	Annotations map[string]string `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A list of single-valued strings, to for example classify catalog entities in various ways.
	Tags []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// A list of external hyperlinks related to the entity.
	Links         []*Link `protobuf:"bytes,8,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Metadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Metadata) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type Link struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Url         string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Icon        string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Type        string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	IsGenerated bool                   `protobuf:"varint,5,opt,name=is_generated,json=isGenerated,proto3" json:"is_generated,omitempty"`
	// Set for auto-generated multi-environment links. Non-nil links with the
	// same group_info.group are rendered together in the UI.
	GroupInfo     *LinkGroupInfo `protobuf:"bytes,6,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Link) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Link) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Link) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Link) GetIsGenerated() bool {
	if x != nil {
		return x.IsGenerated
	}
	return false
}

func (x *Link) GetGroupInfo() *LinkGroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

// LinkGroupInfo groups multiple links (e.g. one per environment) under a
// shared display title. A nil value means the link is standalone.
type LinkGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"` // shared display title for the group, e.g. "Monitoring"
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // per-link label within the group, e.g. "dev", "prod"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkGroupInfo) Reset() {
	*x = LinkGroupInfo{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkGroupInfo) ProtoMessage() {}

func (x *LinkGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkGroupInfo.ProtoReflect.Descriptor instead.
func (*LinkGroupInfo) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *LinkGroupInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *LinkGroupInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Ref represents a reference to another entity.
type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Ref) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Ref) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Ref) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// LabelRef represents a reference with an optional label and attributes.
type LabelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelRef) Reset() {
	*x = LabelRef{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelRef) ProtoMessage() {}

func (x *LabelRef) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelRef.ProtoReflect.Descriptor instead.
func (*LabelRef) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *LabelRef) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *LabelRef) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabelRef) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawVersion    string                 `protobuf:"bytes,1,opt,name=raw_version,json=rawVersion,proto3" json:"raw_version,omitempty"`
	Major         int32                  `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor         int32                  `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         int32                  `protobuf:"varint,4,opt,name=patch,proto3" json:"patch,omitempty"`
	Suffix        string                 `protobuf:"bytes,5,opt,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Version) GetRawVersion() string {
	if x != nil {
		return x.RawVersion
	}
	return ""
}

func (x *Version) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Version) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Version) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *Version) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

// Entity represents any catalog entity.
type Entity struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Kind     string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Spec:
	//
	//	*Entity_DomainSpec
	//	*Entity_SystemSpec
	//	*Entity_ComponentSpec
	//	*Entity_ResourceSpec
	//	*Entity_ApiSpec
	//	*Entity_GroupSpec
	Spec isEntity_Spec `protobuf_oneof:"spec"`
	// Runtime status. Not persisted in the repository, but populated at runtime
	// (e.g. by plugins). Always nil for Group entities.
	Status        *Status `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *Entity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Entity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Entity) GetSpec() isEntity_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Entity) GetDomainSpec() *DomainSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_DomainSpec); ok {
			return x.DomainSpec
		}
	}
	return nil
}

func (x *Entity) GetSystemSpec() *SystemSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_SystemSpec); ok {
			return x.SystemSpec
		}
	}
	return nil
}

func (x *Entity) GetComponentSpec() *ComponentSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_ComponentSpec); ok {
			return x.ComponentSpec
		}
	}
	return nil
}

func (x *Entity) GetResourceSpec() *ResourceSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_ResourceSpec); ok {
			return x.ResourceSpec
		}
	}
	return nil
}

func (x *Entity) GetApiSpec() *ApiSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_ApiSpec); ok {
			return x.ApiSpec
		}
	}
	return nil
}

func (x *Entity) GetGroupSpec() *GroupSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_GroupSpec); ok {
			return x.GroupSpec
		}
	}
	return nil
}

func (x *Entity) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type isEntity_Spec interface {
	isEntity_Spec()
}

type Entity_DomainSpec struct {
	DomainSpec *DomainSpec `protobuf:"bytes,3,opt,name=domain_spec,json=domainSpec,proto3,oneof"`
}

type Entity_SystemSpec struct {
	SystemSpec *SystemSpec `protobuf:"bytes,4,opt,name=system_spec,json=systemSpec,proto3,oneof"`
}

type Entity_ComponentSpec struct {
	ComponentSpec *ComponentSpec `protobuf:"bytes,5,opt,name=component_spec,json=componentSpec,proto3,oneof"`
}

type Entity_ResourceSpec struct {
	ResourceSpec *ResourceSpec `protobuf:"bytes,6,opt,name=resource_spec,json=resourceSpec,proto3,oneof"`
}

type Entity_ApiSpec struct {
	ApiSpec *ApiSpec `protobuf:"bytes,7,opt,name=api_spec,json=apiSpec,proto3,oneof"`
}

type Entity_GroupSpec struct {
	GroupSpec *GroupSpec `protobuf:"bytes,8,opt,name=group_spec,json=groupSpec,proto3,oneof"`
}

func (*Entity_DomainSpec) isEntity_Spec() {}

func (*Entity_SystemSpec) isEntity_Spec() {}

func (*Entity_ComponentSpec) isEntity_Spec() {}

func (*Entity_ResourceSpec) isEntity_Spec() {}

func (*Entity_ApiSpec) isEntity_Spec() {}

func (*Entity_GroupSpec) isEntity_Spec() {}

// ListEntitiesResponse is the response body of GET /catalog/entities.
type ListEntitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntitiesResponse) Reset() {
	*x = ListEntitiesResponse{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntitiesResponse) ProtoMessage() {}

func (x *ListEntitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntitiesResponse.ProtoReflect.Descriptor instead.
func (*ListEntitiesResponse) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ListEntitiesResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

// Status holds runtime observations attached to an entity by plugins.
type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map from observation name (following annotation naming conventions) to
	// status observation.
	Observations  map[string]*Observation `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *Status) GetObservations() map[string]*Observation {
	if x != nil {
		return x.Observations
	}
	return nil
}

type Observation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The observation value as a parsed JSON value, so it round-trips through
	// protojson as native JSON (object/array/number/string/bool/null) rather
	// than a base64-encoded blob.
	Value *structpb.Value `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Identifier of the plugin that produced this observation.
	Producer  string                 `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Optional: the entity version at which this observation was made.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Optional: additional metadata for display in custom content.
	Meta          map[string]string `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *Observation) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Observation) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *Observation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Observation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Observation) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ObservedDependencies is the schema external tools must comply with when
// reporting the dependencies they observed for a single source entity. swcat
// stores these tentative, "observed" dependencies in the source entity's
// Status observations, kept separate from the declared dependencies in the
// entity's spec.
type ObservedDependencies struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the source entity that the observed dependencies originate
	// from. Required.
	Source *Ref `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Label of the external tool that detected these dependencies. Required.
	DetectedBy string `protobuf:"bytes,2,opt,name=detected_by,json=detectedBy,proto3" json:"detected_by,omitempty"`
	// When the dependencies were observed. If unset, the server populates it
	// with the receive timestamp. Maps to Observation.updated_at.
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// The dependencies observed for the source entity. Reporting an empty list
	// clears the previously observed dependencies for this source/detected_by
	// pair.
	Dependencies []*ObservedDependency `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// Optional: the version of the source entity these dependencies were
	// observed for, e.g. "1.4.2". Maps to Observation.version.
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Optional: additional metadata about this observation, for display in
	// custom content. Maps to Observation.meta.
	Meta          map[string]string `protobuf:"bytes,6,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedDependencies) Reset() {
	*x = ObservedDependencies{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedDependencies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedDependencies) ProtoMessage() {}

func (x *ObservedDependencies) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedDependencies.ProtoReflect.Descriptor instead.
func (*ObservedDependencies) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *ObservedDependencies) GetSource() *Ref {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ObservedDependencies) GetDetectedBy() string {
	if x != nil {
		return x.DetectedBy
	}
	return ""
}

func (x *ObservedDependencies) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *ObservedDependencies) GetDependencies() []*ObservedDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *ObservedDependencies) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ObservedDependencies) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// ObservedDependency is a single dependency from a source entity to a target
// entity, as detected by an external tool.
type ObservedDependency struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the entity that the source entity depends on. Required.
	Target *Ref `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// The nature of the dependency relationship.
	Relation DependencyRelation `protobuf:"varint,2,opt,name=relation,proto3,enum=swcat.catalog.v1.DependencyRelation" json:"relation,omitempty"`
	// The evidence on which the detection was based, e.g. a list of topic names,
	// an RPC Service.Method name, or other relevant detail.
	Evidence      []string `protobuf:"bytes,3,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservedDependency) Reset() {
	*x = ObservedDependency{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedDependency) ProtoMessage() {}

func (x *ObservedDependency) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedDependency.ProtoReflect.Descriptor instead.
func (*ObservedDependency) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *ObservedDependency) GetTarget() *Ref {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ObservedDependency) GetRelation() DependencyRelation {
	if x != nil {
		return x.Relation
	}
	return DependencyRelation_DEPENDENCY_RELATION_UNSPECIFIED
}

func (x *ObservedDependency) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type DomainSpec struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Owner       *Ref                   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	SubdomainOf *Ref                   `protobuf:"bytes,2,opt,name=subdomain_of,json=subdomainOf,proto3" json:"subdomain_of,omitempty"`
	Type        string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Inverse relationships
	Systems       []*Ref `protobuf:"bytes,4,rep,name=systems,proto3" json:"systems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainSpec) Reset() {
	*x = DomainSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainSpec) ProtoMessage() {}

func (x *DomainSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainSpec.ProtoReflect.Descriptor instead.
func (*DomainSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *DomainSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *DomainSpec) GetSubdomainOf() *Ref {
	if x != nil {
		return x.SubdomainOf
	}
	return nil
}

func (x *DomainSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DomainSpec) GetSystems() []*Ref {
	if x != nil {
		return x.Systems
	}
	return nil
}

type SystemSpec struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Owner  *Ref                   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Domain *Ref                   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Type   string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Inverse relationships
	Components    []*Ref `protobuf:"bytes,4,rep,name=components,proto3" json:"components,omitempty"`
	Apis          []*Ref `protobuf:"bytes,5,rep,name=apis,proto3" json:"apis,omitempty"`
	Resources     []*Ref `protobuf:"bytes,6,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemSpec) Reset() {
	*x = SystemSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSpec) ProtoMessage() {}

func (x *SystemSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSpec.ProtoReflect.Descriptor instead.
func (*SystemSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *SystemSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SystemSpec) GetDomain() *Ref {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *SystemSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SystemSpec) GetComponents() []*Ref {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *SystemSpec) GetApis() []*Ref {
	if x != nil {
		return x.Apis
	}
	return nil
}

func (x *SystemSpec) GetResources() []*Ref {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ComponentSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Lifecycle      string                 `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	Owner          *Ref                   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	System         *Ref                   `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	Domain         *Ref                   `protobuf:"bytes,11,opt,name=domain,proto3" json:"domain,omitempty"`
	SubcomponentOf *Ref                   `protobuf:"bytes,5,opt,name=subcomponent_of,json=subcomponentOf,proto3" json:"subcomponent_of,omitempty"`
	ProvidesApis   []*LabelRef            `protobuf:"bytes,6,rep,name=provides_apis,json=providesApis,proto3" json:"provides_apis,omitempty"`
	ConsumesApis   []*LabelRef            `protobuf:"bytes,7,rep,name=consumes_apis,json=consumesApis,proto3" json:"consumes_apis,omitempty"`
	DependsOn      []*LabelRef            `protobuf:"bytes,8,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	// Inverse relationships
	Dependents    []*LabelRef `protobuf:"bytes,9,rep,name=dependents,proto3" json:"dependents,omitempty"`
	Subcomponents []*Ref      `protobuf:"bytes,10,rep,name=subcomponents,proto3" json:"subcomponents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentSpec) Reset() {
	*x = ComponentSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentSpec) ProtoMessage() {}

func (x *ComponentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentSpec.ProtoReflect.Descriptor instead.
func (*ComponentSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *ComponentSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ComponentSpec) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

func (x *ComponentSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ComponentSpec) GetSystem() *Ref {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *ComponentSpec) GetDomain() *Ref {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *ComponentSpec) GetSubcomponentOf() *Ref {
	if x != nil {
		return x.SubcomponentOf
	}
	return nil
}

func (x *ComponentSpec) GetProvidesApis() []*LabelRef {
	if x != nil {
		return x.ProvidesApis
	}
	return nil
}

func (x *ComponentSpec) GetConsumesApis() []*LabelRef {
	if x != nil {
		return x.ConsumesApis
	}
	return nil
}

func (x *ComponentSpec) GetDependsOn() []*LabelRef {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *ComponentSpec) GetDependents() []*LabelRef {
	if x != nil {
		return x.Dependents
	}
	return nil
}

func (x *ComponentSpec) GetSubcomponents() []*Ref {
	if x != nil {
		return x.Subcomponents
	}
	return nil
}

type ResourceSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Owner     *Ref                   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	System    *Ref                   `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"`
	Domain    *Ref                   `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	DependsOn []*LabelRef            `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	// Inverse relationships
	Dependents    []*LabelRef `protobuf:"bytes,5,rep,name=dependents,proto3" json:"dependents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *ResourceSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ResourceSpec) GetSystem() *Ref {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *ResourceSpec) GetDomain() *Ref {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *ResourceSpec) GetDependsOn() []*LabelRef {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *ResourceSpec) GetDependents() []*LabelRef {
	if x != nil {
		return x.Dependents
	}
	return nil
}

type ApiSpec struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Type       string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Lifecycle  string                 `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	Owner      *Ref                   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	System     *Ref                   `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	Domain     *Ref                   `protobuf:"bytes,9,opt,name=domain,proto3" json:"domain,omitempty"`
	Definition string                 `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	Versions   []*ApiSpecVersion      `protobuf:"bytes,6,rep,name=versions,proto3" json:"versions,omitempty"`
	// Inverse relationships
	Providers     []*LabelRef `protobuf:"bytes,7,rep,name=providers,proto3" json:"providers,omitempty"`
	Consumers     []*LabelRef `protobuf:"bytes,8,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiSpec) Reset() {
	*x = ApiSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiSpec) ProtoMessage() {}

func (x *ApiSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiSpec.ProtoReflect.Descriptor instead.
func (*ApiSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *ApiSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApiSpec) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

func (x *ApiSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ApiSpec) GetSystem() *Ref {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *ApiSpec) GetDomain() *Ref {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *ApiSpec) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *ApiSpec) GetVersions() []*ApiSpecVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ApiSpec) GetProviders() []*LabelRef {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ApiSpec) GetConsumers() []*LabelRef {
	if x != nil {
		return x.Consumers
	}
	return nil
}

type ApiSpecVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Lifecycle     string                 `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiSpecVersion) Reset() {
	*x = ApiSpecVersion{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiSpecVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiSpecVersion) ProtoMessage() {}

func (x *ApiSpecVersion) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiSpecVersion.ProtoReflect.Descriptor instead.
func (*ApiSpecVersion) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *ApiSpecVersion) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ApiSpecVersion) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

type GroupSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Profile       *GroupSpecProfile      `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Parent        *Ref                   `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Children      []*Ref                 `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	Members       []string               `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSpec) Reset() {
	*x = GroupSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSpec) ProtoMessage() {}

func (x *GroupSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSpec.ProtoReflect.Descriptor instead.
func (*GroupSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *GroupSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GroupSpec) GetProfile() *GroupSpecProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GroupSpec) GetParent() *Ref {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *GroupSpec) GetChildren() []*Ref {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *GroupSpec) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type GroupSpecProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Picture       string                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSpecProfile) Reset() {
	*x = GroupSpecProfile{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSpecProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSpecProfile) ProtoMessage() {}

func (x *GroupSpecProfile) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSpecProfile.ProtoReflect.Descriptor instead.
func (*GroupSpecProfile) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *GroupSpecProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GroupSpecProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GroupSpecProfile) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

var File_swcat_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_swcat_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1eswcat/catalog/v1/catalog.proto\x12\x10swcat.catalog.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc0\x03\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12>\n" +
	"\x06labels\x18\x05 \x03(\v2&.swcat.catalog.v1.Metadata.LabelsEntryR\x06labels\x12M\n" +
	"\vannotations\x18\x06 \x03(\v2+.swcat.catalog.v1.Metadata.AnnotationsEntryR\vannotations\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12,\n" +
	"\x05links\x18\b \x03(\v2\x16.swcat.catalog.v1.LinkR\x05links\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x04Link\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12!\n" +
	"\fis_generated\x18\x05 \x01(\bR\visGenerated\x12>\n" +
	"\n" +
	"group_info\x18\x06 \x01(\v2\x1f.swcat.catalog.v1.LinkGroupInfoR\tgroupInfo\";\n" +
	"\rLinkGroupInfo\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"K\n" +
	"\x03Ref\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xc0\x01\n" +
	"\bLabelRef\x12'\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.swcat.catalog.v1.RefR\x03ref\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12;\n" +
	"\x05attrs\x18\x03 \x03(\v2%.swcat.catalog.v1.LabelRef.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\aVersion\x12\x1f\n" +
	"\vraw_version\x18\x01 \x01(\tR\n" +
	"rawVersion\x12\x14\n" +
	"\x05major\x18\x02 \x01(\x05R\x05major\x12\x14\n" +
	"\x05minor\x18\x03 \x01(\x05R\x05minor\x12\x14\n" +
	"\x05patch\x18\x04 \x01(\x05R\x05patch\x12\x16\n" +
	"\x06suffix\x18\x05 \x01(\tR\x06suffix\"\x97\x04\n" +
	"\x06Entity\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x126\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.swcat.catalog.v1.MetadataR\bmetadata\x12?\n" +
	"\vdomain_spec\x18\x03 \x01(\v2\x1c.swcat.catalog.v1.DomainSpecH\x00R\n" +
	"domainSpec\x12?\n" +
	"\vsystem_spec\x18\x04 \x01(\v2\x1c.swcat.catalog.v1.SystemSpecH\x00R\n" +
	"systemSpec\x12H\n" +
	"\x0ecomponent_spec\x18\x05 \x01(\v2\x1f.swcat.catalog.v1.ComponentSpecH\x00R\rcomponentSpec\x12E\n" +
	"\rresource_spec\x18\x06 \x01(\v2\x1e.swcat.catalog.v1.ResourceSpecH\x00R\fresourceSpec\x126\n" +
	"\bapi_spec\x18\a \x01(\v2\x19.swcat.catalog.v1.ApiSpecH\x00R\aapiSpec\x12<\n" +
	"\n" +
	"group_spec\x18\b \x01(\v2\x1b.swcat.catalog.v1.GroupSpecH\x00R\tgroupSpec\x120\n" +
	"\x06status\x18\t \x01(\v2\x18.swcat.catalog.v1.StatusR\x06statusB\x06\n" +
	"\x04spec\"L\n" +
	"\x14ListEntitiesResponse\x124\n" +
	"\bentities\x18\x01 \x03(\v2\x18.swcat.catalog.v1.EntityR\bentities\"\xb8\x01\n" +
	"\x06Status\x12N\n" +
	"\fobservations\x18\x01 \x03(\v2*.swcat.catalog.v1.Status.ObservationsEntryR\fobservations\x1a^\n" +
	"\x11ObservationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.swcat.catalog.v1.ObservationR\x05value:\x028\x01\"\xa2\x02\n" +
	"\vObservation\x12,\n" +
	"\x05value\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12\x1a\n" +
	"\bproducer\x18\x02 \x01(\tR\bproducer\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12;\n" +
	"\x04meta\x18\x05 \x03(\v2'.swcat.catalog.v1.Observation.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x03\n" +
	"\x14ObservedDependencies\x12-\n" +
	"\x06source\x18\x01 \x01(\v2\x15.swcat.catalog.v1.RefR\x06source\x12\x1f\n" +
	"\vdetected_by\x18\x02 \x01(\tR\n" +
	"detectedBy\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12H\n" +
	"\fdependencies\x18\x04 \x03(\v2$.swcat.catalog.v1.ObservedDependencyR\fdependencies\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12D\n" +
	"\x04meta\x18\x06 \x03(\v20.swcat.catalog.v1.ObservedDependencies.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\x12ObservedDependency\x12-\n" +
	"\x06target\x18\x01 \x01(\v2\x15.swcat.catalog.v1.RefR\x06target\x12@\n" +
	"\brelation\x18\x02 \x01(\x0e2$.swcat.catalog.v1.DependencyRelationR\brelation\x12\x1a\n" +
	"\bevidence\x18\x03 \x03(\tR\bevidence\"\xb8\x01\n" +
	"\n" +
	"DomainSpec\x12+\n" +
	"\x05owner\x18\x01 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x128\n" +
	"\fsubdomain_of\x18\x02 \x01(\v2\x15.swcat.catalog.v1.RefR\vsubdomainOf\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12/\n" +
	"\asystems\x18\x04 \x03(\v2\x15.swcat.catalog.v1.RefR\asystems\"\x93\x02\n" +
	"\n" +
	"SystemSpec\x12+\n" +
	"\x05owner\x18\x01 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x12-\n" +
	"\x06domain\x18\x02 \x01(\v2\x15.swcat.catalog.v1.RefR\x06domain\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x125\n" +
	"\n" +
	"components\x18\x04 \x03(\v2\x15.swcat.catalog.v1.RefR\n" +
	"components\x12)\n" +
	"\x04apis\x18\x05 \x03(\v2\x15.swcat.catalog.v1.RefR\x04apis\x123\n" +
	"\tresources\x18\x06 \x03(\v2\x15.swcat.catalog.v1.RefR\tresources\"\xc2\x04\n" +
	"\rComponentSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\tlifecycle\x18\x02 \x01(\tR\tlifecycle\x12+\n" +
	"\x05owner\x18\x03 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x12-\n" +
	"\x06system\x18\x04 \x01(\v2\x15.swcat.catalog.v1.RefR\x06system\x12-\n" +
	"\x06domain\x18\v \x01(\v2\x15.swcat.catalog.v1.RefR\x06domain\x12>\n" +
	"\x0fsubcomponent_of\x18\x05 \x01(\v2\x15.swcat.catalog.v1.RefR\x0esubcomponentOf\x12?\n" +
	"\rprovides_apis\x18\x06 \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\fprovidesApis\x12?\n" +
	"\rconsumes_apis\x18\a \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\fconsumesApis\x129\n" +
	"\n" +
	"depends_on\x18\b \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\tdependsOn\x12:\n" +
	"\n" +
	"dependents\x18\t \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\n" +
	"dependents\x12;\n" +
	"\rsubcomponents\x18\n" +
	" \x03(\v2\x15.swcat.catalog.v1.RefR\rsubcomponents\"\xa4\x02\n" +
	"\fResourceSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12+\n" +
	"\x05owner\x18\x02 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x12-\n" +
	"\x06system\x18\x03 \x01(\v2\x15.swcat.catalog.v1.RefR\x06system\x12-\n" +
	"\x06domain\x18\x06 \x01(\v2\x15.swcat.catalog.v1.RefR\x06domain\x129\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\tdependsOn\x12:\n" +
	"\n" +
	"dependents\x18\x05 \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\n" +
	"dependents\"\x98\x03\n" +
	"\aApiSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\tlifecycle\x18\x02 \x01(\tR\tlifecycle\x12+\n" +
	"\x05owner\x18\x03 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x12-\n" +
	"\x06system\x18\x04 \x01(\v2\x15.swcat.catalog.v1.RefR\x06system\x12-\n" +
	"\x06domain\x18\t \x01(\v2\x15.swcat.catalog.v1.RefR\x06domain\x12\x1e\n" +
	"\n" +
	"definition\x18\x05 \x01(\tR\n" +
	"definition\x12<\n" +
	"\bversions\x18\x06 \x03(\v2 .swcat.catalog.v1.ApiSpecVersionR\bversions\x128\n" +
	"\tproviders\x18\a \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\tproviders\x128\n" +
	"\tconsumers\x18\b \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\tconsumers\"c\n" +
	"\x0eApiSpecVersion\x123\n" +
	"\aversion\x18\x01 \x01(\v2\x19.swcat.catalog.v1.VersionR\aversion\x12\x1c\n" +
	"\tlifecycle\x18\x02 \x01(\tR\tlifecycle\"\xd9\x01\n" +
	"\tGroupSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12<\n" +
	"\aprofile\x18\x02 \x01(\v2\".swcat.catalog.v1.GroupSpecProfileR\aprofile\x12-\n" +
	"\x06parent\x18\x03 \x01(\v2\x15.swcat.catalog.v1.RefR\x06parent\x121\n" +
	"\bchildren\x18\x04 \x03(\v2\x15.swcat.catalog.v1.RefR\bchildren\x12\x18\n" +
	"\amembers\x18\x05 \x03(\tR\amembers\"e\n" +
	"\x10GroupSpecProfile\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\apicture\x18\x03 \x01(\tR\apicture*\x9c\x01\n" +
	"\x12DependencyRelation\x12#\n" +
	"\x1fDEPENDENCY_RELATION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DEPENDENCY_RELATION_CALLS\x10\x01\x12 \n" +
	"\x1cDEPENDENCY_RELATION_PRODUCES\x10\x02\x12 \n" +
	"\x1cDEPENDENCY_RELATION_CONSUMES\x10\x03B8Z6github.com/dnswlt/swcat/internal/catalog/pb;catalog_pbb\x06proto3"

var (
	file_swcat_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_swcat_catalog_v1_catalog_proto_rawDescData []byte
)

func file_swcat_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_swcat_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_swcat_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swcat_catalog_v1_catalog_proto_rawDesc), len(file_swcat_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_swcat_catalog_v1_catalog_proto_rawDescData
}

var file_swcat_catalog_v1_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_swcat_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_swcat_catalog_v1_catalog_proto_goTypes = []any{
	(DependencyRelation)(0),       // 0: swcat.catalog.v1.DependencyRelation
	(*Metadata)(nil),              // 1: swcat.catalog.v1.Metadata
	(*Link)(nil),                  // 2: swcat.catalog.v1.Link
	(*LinkGroupInfo)(nil),         // 3: swcat.catalog.v1.LinkGroupInfo
	(*Ref)(nil),                   // 4: swcat.catalog.v1.Ref
	(*LabelRef)(nil),              // 5: swcat.catalog.v1.LabelRef
	(*Version)(nil),               // 6: swcat.catalog.v1.Version
	(*Entity)(nil),                // 7: swcat.catalog.v1.Entity
	(*ListEntitiesResponse)(nil),  // 8: swcat.catalog.v1.ListEntitiesResponse
	(*Status)(nil),                // 9: swcat.catalog.v1.Status
	(*Observation)(nil),           // 10: swcat.catalog.v1.Observation
	(*ObservedDependencies)(nil),  // 11: swcat.catalog.v1.ObservedDependencies
	(*ObservedDependency)(nil),    // 12: swcat.catalog.v1.ObservedDependency
	(*DomainSpec)(nil),            // 13: swcat.catalog.v1.DomainSpec
	(*SystemSpec)(nil),            // 14: swcat.catalog.v1.SystemSpec
	(*ComponentSpec)(nil),         // 15: swcat.catalog.v1.ComponentSpec
	(*ResourceSpec)(nil),          // 16: swcat.catalog.v1.ResourceSpec
	(*ApiSpec)(nil),               // 17: swcat.catalog.v1.ApiSpec
	(*ApiSpecVersion)(nil),        // 18: swcat.catalog.v1.ApiSpecVersion
	(*GroupSpec)(nil),             // 19: swcat.catalog.v1.GroupSpec
	(*GroupSpecProfile)(nil),      // 20: swcat.catalog.v1.GroupSpecProfile
	nil,                           // 21: swcat.catalog.v1.Metadata.LabelsEntry
	nil,                           // 22: swcat.catalog.v1.Metadata.AnnotationsEntry
	nil,                           // 23: swcat.catalog.v1.LabelRef.AttrsEntry
	nil,                           // 24: swcat.catalog.v1.Status.ObservationsEntry
	nil,                           // 25: swcat.catalog.v1.Observation.MetaEntry
	nil,                           // 26: swcat.catalog.v1.ObservedDependencies.MetaEntry
	(*structpb.Value)(nil),        // 27: google.protobuf.Value
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
}
var file_swcat_catalog_v1_catalog_proto_depIdxs = []int32{
	21, // 0: swcat.catalog.v1.Metadata.labels:type_name -> swcat.catalog.v1.Metadata.LabelsEntry
	22, // 1: swcat.catalog.v1.Metadata.annotations:type_name -> swcat.catalog.v1.Metadata.AnnotationsEntry
	2,  // 2: swcat.catalog.v1.Metadata.links:type_name -> swcat.catalog.v1.Link
	3,  // 3: swcat.catalog.v1.Link.group_info:type_name -> swcat.catalog.v1.LinkGroupInfo
	4,  // 4: swcat.catalog.v1.LabelRef.ref:type_name -> swcat.catalog.v1.Ref
	23, // 5: swcat.catalog.v1.LabelRef.attrs:type_name -> swcat.catalog.v1.LabelRef.AttrsEntry
	1,  // 6: swcat.catalog.v1.Entity.metadata:type_name -> swcat.catalog.v1.Metadata
	13, // 7: swcat.catalog.v1.Entity.domain_spec:type_name -> swcat.catalog.v1.DomainSpec
	14, // 8: swcat.catalog.v1.Entity.system_spec:type_name -> swcat.catalog.v1.SystemSpec
	15, // 9: swcat.catalog.v1.Entity.component_spec:type_name -> swcat.catalog.v1.ComponentSpec
	16, // 10: swcat.catalog.v1.Entity.resource_spec:type_name -> swcat.catalog.v1.ResourceSpec
	17, // 11: swcat.catalog.v1.Entity.api_spec:type_name -> swcat.catalog.v1.ApiSpec
	19, // 12: swcat.catalog.v1.Entity.group_spec:type_name -> swcat.catalog.v1.GroupSpec
	9,  // 13: swcat.catalog.v1.Entity.status:type_name -> swcat.catalog.v1.Status
	7,  // 14: swcat.catalog.v1.ListEntitiesResponse.entities:type_name -> swcat.catalog.v1.Entity
	24, // 15: swcat.catalog.v1.Status.observations:type_name -> swcat.catalog.v1.Status.ObservationsEntry
	27, // 16: swcat.catalog.v1.Observation.value:type_name -> google.protobuf.Value
	28, // 17: swcat.catalog.v1.Observation.updated_at:type_name -> google.protobuf.Timestamp
	25, // 18: swcat.catalog.v1.Observation.meta:type_name -> swcat.catalog.v1.Observation.MetaEntry
	4,  // 19: swcat.catalog.v1.ObservedDependencies.source:type_name -> swcat.catalog.v1.Ref
	28, // 20: swcat.catalog.v1.ObservedDependencies.observed_at:type_name -> google.protobuf.Timestamp
	12, // 21: swcat.catalog.v1.ObservedDependencies.dependencies:type_name -> swcat.catalog.v1.ObservedDependency
	26, // 22: swcat.catalog.v1.ObservedDependencies.meta:type_name -> swcat.catalog.v1.ObservedDependencies.MetaEntry
	4,  // 23: swcat.catalog.v1.ObservedDependency.target:type_name -> swcat.catalog.v1.Ref
	0,  // 24: swcat.catalog.v1.ObservedDependency.relation:type_name -> swcat.catalog.v1.DependencyRelation
	4,  // 25: swcat.catalog.v1.DomainSpec.owner:type_name -> swcat.catalog.v1.Ref
	4,  // 26: swcat.catalog.v1.DomainSpec.subdomain_of:type_name -> swcat.catalog.v1.Ref
	4,  // 27: swcat.catalog.v1.DomainSpec.systems:type_name -> swcat.catalog.v1.Ref
	4,  // 28: swcat.catalog.v1.SystemSpec.owner:type_name -> swcat.catalog.v1.Ref
	4,  // 29: swcat.catalog.v1.SystemSpec.domain:type_name -> swcat.catalog.v1.Ref
	4,  // 30: swcat.catalog.v1.SystemSpec.components:type_name -> swcat.catalog.v1.Ref
	4,  // 31: swcat.catalog.v1.SystemSpec.apis:type_name -> swcat.catalog.v1.Ref
	4,  // 32: swcat.catalog.v1.SystemSpec.resources:type_name -> swcat.catalog.v1.Ref
	4,  // 33: swcat.catalog.v1.ComponentSpec.owner:type_name -> swcat.catalog.v1.Ref
	4,  // 34: swcat.catalog.v1.ComponentSpec.system:type_name -> swcat.catalog.v1.Ref
	4,  // 35: swcat.catalog.v1.ComponentSpec.domain:type_name -> swcat.catalog.v1.Ref
	4,  // 36: swcat.catalog.v1.ComponentSpec.subcomponent_of:type_name -> swcat.catalog.v1.Ref
	5,  // 37: swcat.catalog.v1.ComponentSpec.provides_apis:type_name -> swcat.catalog.v1.LabelRef
	5,  // 38: swcat.catalog.v1.ComponentSpec.consumes_apis:type_name -> swcat.catalog.v1.LabelRef
	5,  // 39: swcat.catalog.v1.ComponentSpec.depends_on:type_name -> swcat.catalog.v1.LabelRef
	5,  // 40: swcat.catalog.v1.ComponentSpec.dependents:type_name -> swcat.catalog.v1.LabelRef
	4,  // 41: swcat.catalog.v1.ComponentSpec.subcomponents:type_name -> swcat.catalog.v1.Ref
	4,  // 42: swcat.catalog.v1.ResourceSpec.owner:type_name -> swcat.catalog.v1.Ref
	4,  // 43: swcat.catalog.v1.ResourceSpec.system:type_name -> swcat.catalog.v1.Ref
	4,  // 44: swcat.catalog.v1.ResourceSpec.domain:type_name -> swcat.catalog.v1.Ref
	5,  // 45: swcat.catalog.v1.ResourceSpec.depends_on:type_name -> swcat.catalog.v1.LabelRef
	5,  // 46: swcat.catalog.v1.ResourceSpec.dependents:type_name -> swcat.catalog.v1.LabelRef
	4,  // 47: swcat.catalog.v1.ApiSpec.owner:type_name -> swcat.catalog.v1.Ref
	4,  // 48: swcat.catalog.v1.ApiSpec.system:type_name -> swcat.catalog.v1.Ref
	4,  // 49: swcat.catalog.v1.ApiSpec.domain:type_name -> swcat.catalog.v1.Ref
	18, // 50: swcat.catalog.v1.ApiSpec.versions:type_name -> swcat.catalog.v1.ApiSpecVersion
	5,  // 51: swcat.catalog.v1.ApiSpec.providers:type_name -> swcat.catalog.v1.LabelRef
	5,  // 52: swcat.catalog.v1.ApiSpec.consumers:type_name -> swcat.catalog.v1.LabelRef
	6,  // 53: swcat.catalog.v1.ApiSpecVersion.version:type_name -> swcat.catalog.v1.Version
	20, // 54: swcat.catalog.v1.GroupSpec.profile:type_name -> swcat.catalog.v1.GroupSpecProfile
	4,  // 55: swcat.catalog.v1.GroupSpec.parent:type_name -> swcat.catalog.v1.Ref
	4,  // 56: swcat.catalog.v1.GroupSpec.children:type_name -> swcat.catalog.v1.Ref
	10, // 57: swcat.catalog.v1.Status.ObservationsEntry.value:type_name -> swcat.catalog.v1.Observation
	58, // [58:58] is the sub-list for method output_type
	58, // [58:58] is the sub-list for method input_type
	58, // [58:58] is the sub-list for extension type_name
	58, // [58:58] is the sub-list for extension extendee
	0,  // [0:58] is the sub-list for field type_name
}

func init() { file_swcat_catalog_v1_catalog_proto_init() }
func file_swcat_catalog_v1_catalog_proto_init() {
	if File_swcat_catalog_v1_catalog_proto != nil {
		return
	}
	file_swcat_catalog_v1_catalog_proto_msgTypes[6].OneofWrappers = []any{
		(*Entity_DomainSpec)(nil),
		(*Entity_SystemSpec)(nil),
		(*Entity_ComponentSpec)(nil),
		(*Entity_ResourceSpec)(nil),
		(*Entity_ApiSpec)(nil),
		(*Entity_GroupSpec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swcat_catalog_v1_catalog_proto_rawDesc), len(file_swcat_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swcat_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_swcat_catalog_v1_catalog_proto_depIdxs,
		EnumInfos:         file_swcat_catalog_v1_catalog_proto_enumTypes,
		MessageInfos:      file_swcat_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_swcat_catalog_v1_catalog_proto = out.File
	file_swcat_catalog_v1_catalog_proto_goTypes = nil
	file_swcat_catalog_v1_catalog_proto_depIdxs = nil
}
