// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.27.2
// source: swcat/catalog/v1/catalog.proto

package catalog_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata common to all entities.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the entity. Must be unique within the catalog at any given point in time, for any given namespace + kind pair.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The namespace that the entity belongs to. If empty, the entity is assume to live in the default namespace.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// A display name of the entity, to be presented in user interfaces instead of the name property, when available.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// A short (typically relatively few words, on one line) description of the entity.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Key/value pairs of identifying information attached to the entity.
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Key/value pairs of non-identifying auxiliary information attached to the entity.
	Annotations map[string]string `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A list of single-valued strings, to for example classify catalog entities in various ways.
	Tags []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// A list of external hyperlinks related to the entity.
	Links         []*Link `protobuf:"bytes,8,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Metadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Metadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Metadata) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	IsGenerated   bool                   `protobuf:"varint,5,opt,name=is_generated,json=isGenerated,proto3" json:"is_generated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Link) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Link) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Link) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Link) GetIsGenerated() bool {
	if x != nil {
		return x.IsGenerated
	}
	return false
}

// Ref represents a reference to another entity.
type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Ref) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Ref) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Ref) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// LabelRef represents a reference with an optional label and attributes.
type LabelRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *Ref                   `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,3,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelRef) Reset() {
	*x = LabelRef{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelRef) ProtoMessage() {}

func (x *LabelRef) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelRef.ProtoReflect.Descriptor instead.
func (*LabelRef) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *LabelRef) GetRef() *Ref {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *LabelRef) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabelRef) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawVersion    string                 `protobuf:"bytes,1,opt,name=raw_version,json=rawVersion,proto3" json:"raw_version,omitempty"`
	Major         int32                  `protobuf:"varint,2,opt,name=major,proto3" json:"major,omitempty"`
	Minor         int32                  `protobuf:"varint,3,opt,name=minor,proto3" json:"minor,omitempty"`
	Patch         int32                  `protobuf:"varint,4,opt,name=patch,proto3" json:"patch,omitempty"`
	Suffix        string                 `protobuf:"bytes,5,opt,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *Version) GetRawVersion() string {
	if x != nil {
		return x.RawVersion
	}
	return ""
}

func (x *Version) GetMajor() int32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Version) GetMinor() int32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Version) GetPatch() int32 {
	if x != nil {
		return x.Patch
	}
	return 0
}

func (x *Version) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

// Entity represents any catalog entity.
type Entity struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Kind     string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Spec:
	//
	//	*Entity_DomainSpec
	//	*Entity_SystemSpec
	//	*Entity_ComponentSpec
	//	*Entity_ResourceSpec
	//	*Entity_ApiSpec
	//	*Entity_GroupSpec
	Spec          isEntity_Spec `protobuf_oneof:"spec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *Entity) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Entity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Entity) GetSpec() isEntity_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Entity) GetDomainSpec() *DomainSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_DomainSpec); ok {
			return x.DomainSpec
		}
	}
	return nil
}

func (x *Entity) GetSystemSpec() *SystemSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_SystemSpec); ok {
			return x.SystemSpec
		}
	}
	return nil
}

func (x *Entity) GetComponentSpec() *ComponentSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_ComponentSpec); ok {
			return x.ComponentSpec
		}
	}
	return nil
}

func (x *Entity) GetResourceSpec() *ResourceSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_ResourceSpec); ok {
			return x.ResourceSpec
		}
	}
	return nil
}

func (x *Entity) GetApiSpec() *ApiSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_ApiSpec); ok {
			return x.ApiSpec
		}
	}
	return nil
}

func (x *Entity) GetGroupSpec() *GroupSpec {
	if x != nil {
		if x, ok := x.Spec.(*Entity_GroupSpec); ok {
			return x.GroupSpec
		}
	}
	return nil
}

type isEntity_Spec interface {
	isEntity_Spec()
}

type Entity_DomainSpec struct {
	DomainSpec *DomainSpec `protobuf:"bytes,3,opt,name=domain_spec,json=domainSpec,proto3,oneof"`
}

type Entity_SystemSpec struct {
	SystemSpec *SystemSpec `protobuf:"bytes,4,opt,name=system_spec,json=systemSpec,proto3,oneof"`
}

type Entity_ComponentSpec struct {
	ComponentSpec *ComponentSpec `protobuf:"bytes,5,opt,name=component_spec,json=componentSpec,proto3,oneof"`
}

type Entity_ResourceSpec struct {
	ResourceSpec *ResourceSpec `protobuf:"bytes,6,opt,name=resource_spec,json=resourceSpec,proto3,oneof"`
}

type Entity_ApiSpec struct {
	ApiSpec *ApiSpec `protobuf:"bytes,7,opt,name=api_spec,json=apiSpec,proto3,oneof"`
}

type Entity_GroupSpec struct {
	GroupSpec *GroupSpec `protobuf:"bytes,8,opt,name=group_spec,json=groupSpec,proto3,oneof"`
}

func (*Entity_DomainSpec) isEntity_Spec() {}

func (*Entity_SystemSpec) isEntity_Spec() {}

func (*Entity_ComponentSpec) isEntity_Spec() {}

func (*Entity_ResourceSpec) isEntity_Spec() {}

func (*Entity_ApiSpec) isEntity_Spec() {}

func (*Entity_GroupSpec) isEntity_Spec() {}

type DomainSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *Ref                   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	SubdomainOf   *Ref                   `protobuf:"bytes,2,opt,name=subdomain_of,json=subdomainOf,proto3" json:"subdomain_of,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainSpec) Reset() {
	*x = DomainSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainSpec) ProtoMessage() {}

func (x *DomainSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainSpec.ProtoReflect.Descriptor instead.
func (*DomainSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *DomainSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *DomainSpec) GetSubdomainOf() *Ref {
	if x != nil {
		return x.SubdomainOf
	}
	return nil
}

func (x *DomainSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SystemSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         *Ref                   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Domain        *Ref                   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemSpec) Reset() {
	*x = SystemSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSpec) ProtoMessage() {}

func (x *SystemSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSpec.ProtoReflect.Descriptor instead.
func (*SystemSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *SystemSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SystemSpec) GetDomain() *Ref {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *SystemSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ComponentSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Lifecycle      string                 `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	Owner          *Ref                   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	System         *Ref                   `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	SubcomponentOf *Ref                   `protobuf:"bytes,5,opt,name=subcomponent_of,json=subcomponentOf,proto3" json:"subcomponent_of,omitempty"`
	ProvidesApis   []*LabelRef            `protobuf:"bytes,6,rep,name=provides_apis,json=providesApis,proto3" json:"provides_apis,omitempty"`
	ConsumesApis   []*LabelRef            `protobuf:"bytes,7,rep,name=consumes_apis,json=consumesApis,proto3" json:"consumes_apis,omitempty"`
	DependsOn      []*LabelRef            `protobuf:"bytes,8,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComponentSpec) Reset() {
	*x = ComponentSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentSpec) ProtoMessage() {}

func (x *ComponentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentSpec.ProtoReflect.Descriptor instead.
func (*ComponentSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *ComponentSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ComponentSpec) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

func (x *ComponentSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ComponentSpec) GetSystem() *Ref {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *ComponentSpec) GetSubcomponentOf() *Ref {
	if x != nil {
		return x.SubcomponentOf
	}
	return nil
}

func (x *ComponentSpec) GetProvidesApis() []*LabelRef {
	if x != nil {
		return x.ProvidesApis
	}
	return nil
}

func (x *ComponentSpec) GetConsumesApis() []*LabelRef {
	if x != nil {
		return x.ConsumesApis
	}
	return nil
}

func (x *ComponentSpec) GetDependsOn() []*LabelRef {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Owner         *Ref                   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	System        *Ref                   `protobuf:"bytes,3,opt,name=system,proto3" json:"system,omitempty"`
	DependsOn     []*LabelRef            `protobuf:"bytes,4,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ResourceSpec) GetSystem() *Ref {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *ResourceSpec) GetDependsOn() []*LabelRef {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type ApiSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Lifecycle     string                 `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	Owner         *Ref                   `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	System        *Ref                   `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	Definition    string                 `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	Versions      []*ApiSpecVersion      `protobuf:"bytes,6,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiSpec) Reset() {
	*x = ApiSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiSpec) ProtoMessage() {}

func (x *ApiSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiSpec.ProtoReflect.Descriptor instead.
func (*ApiSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *ApiSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ApiSpec) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

func (x *ApiSpec) GetOwner() *Ref {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *ApiSpec) GetSystem() *Ref {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *ApiSpec) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *ApiSpec) GetVersions() []*ApiSpecVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ApiSpecVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Lifecycle     string                 `protobuf:"bytes,2,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiSpecVersion) Reset() {
	*x = ApiSpecVersion{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiSpecVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiSpecVersion) ProtoMessage() {}

func (x *ApiSpecVersion) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiSpecVersion.ProtoReflect.Descriptor instead.
func (*ApiSpecVersion) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *ApiSpecVersion) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *ApiSpecVersion) GetLifecycle() string {
	if x != nil {
		return x.Lifecycle
	}
	return ""
}

type GroupSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Profile       *GroupSpecProfile      `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Parent        *Ref                   `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Children      []*Ref                 `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	Members       []string               `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSpec) Reset() {
	*x = GroupSpec{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSpec) ProtoMessage() {}

func (x *GroupSpec) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSpec.ProtoReflect.Descriptor instead.
func (*GroupSpec) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *GroupSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GroupSpec) GetProfile() *GroupSpecProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GroupSpec) GetParent() *Ref {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *GroupSpec) GetChildren() []*Ref {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *GroupSpec) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type GroupSpecProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Picture       string                 `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSpecProfile) Reset() {
	*x = GroupSpecProfile{}
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSpecProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSpecProfile) ProtoMessage() {}

func (x *GroupSpecProfile) ProtoReflect() protoreflect.Message {
	mi := &file_swcat_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSpecProfile.ProtoReflect.Descriptor instead.
func (*GroupSpecProfile) Descriptor() ([]byte, []int) {
	return file_swcat_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *GroupSpecProfile) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GroupSpecProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GroupSpecProfile) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

var File_swcat_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_swcat_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1eswcat/catalog/v1/catalog.proto\x12\x10swcat.catalog.v1\"\xc0\x03\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12>\n" +
	"\x06labels\x18\x05 \x03(\v2&.swcat.catalog.v1.Metadata.LabelsEntryR\x06labels\x12M\n" +
	"\vannotations\x18\x06 \x03(\v2+.swcat.catalog.v1.Metadata.AnnotationsEntryR\vannotations\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12,\n" +
	"\x05links\x18\b \x03(\v2\x16.swcat.catalog.v1.LinkR\x05links\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x04Link\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12!\n" +
	"\fis_generated\x18\x05 \x01(\bR\visGenerated\"K\n" +
	"\x03Ref\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xc0\x01\n" +
	"\bLabelRef\x12'\n" +
	"\x03ref\x18\x01 \x01(\v2\x15.swcat.catalog.v1.RefR\x03ref\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12;\n" +
	"\x05attrs\x18\x03 \x03(\v2%.swcat.catalog.v1.LabelRef.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\aVersion\x12\x1f\n" +
	"\vraw_version\x18\x01 \x01(\tR\n" +
	"rawVersion\x12\x14\n" +
	"\x05major\x18\x02 \x01(\x05R\x05major\x12\x14\n" +
	"\x05minor\x18\x03 \x01(\x05R\x05minor\x12\x14\n" +
	"\x05patch\x18\x04 \x01(\x05R\x05patch\x12\x16\n" +
	"\x06suffix\x18\x05 \x01(\tR\x06suffix\"\xe5\x03\n" +
	"\x06Entity\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x126\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1a.swcat.catalog.v1.MetadataR\bmetadata\x12?\n" +
	"\vdomain_spec\x18\x03 \x01(\v2\x1c.swcat.catalog.v1.DomainSpecH\x00R\n" +
	"domainSpec\x12?\n" +
	"\vsystem_spec\x18\x04 \x01(\v2\x1c.swcat.catalog.v1.SystemSpecH\x00R\n" +
	"systemSpec\x12H\n" +
	"\x0ecomponent_spec\x18\x05 \x01(\v2\x1f.swcat.catalog.v1.ComponentSpecH\x00R\rcomponentSpec\x12E\n" +
	"\rresource_spec\x18\x06 \x01(\v2\x1e.swcat.catalog.v1.ResourceSpecH\x00R\fresourceSpec\x126\n" +
	"\bapi_spec\x18\a \x01(\v2\x19.swcat.catalog.v1.ApiSpecH\x00R\aapiSpec\x12<\n" +
	"\n" +
	"group_spec\x18\b \x01(\v2\x1b.swcat.catalog.v1.GroupSpecH\x00R\tgroupSpecB\x06\n" +
	"\x04spec\"\x87\x01\n" +
	"\n" +
	"DomainSpec\x12+\n" +
	"\x05owner\x18\x01 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x128\n" +
	"\fsubdomain_of\x18\x02 \x01(\v2\x15.swcat.catalog.v1.RefR\vsubdomainOf\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"|\n" +
	"\n" +
	"SystemSpec\x12+\n" +
	"\x05owner\x18\x01 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x12-\n" +
	"\x06domain\x18\x02 \x01(\v2\x15.swcat.catalog.v1.RefR\x06domain\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\x9a\x03\n" +
	"\rComponentSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\tlifecycle\x18\x02 \x01(\tR\tlifecycle\x12+\n" +
	"\x05owner\x18\x03 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x12-\n" +
	"\x06system\x18\x04 \x01(\v2\x15.swcat.catalog.v1.RefR\x06system\x12>\n" +
	"\x0fsubcomponent_of\x18\x05 \x01(\v2\x15.swcat.catalog.v1.RefR\x0esubcomponentOf\x12?\n" +
	"\rprovides_apis\x18\x06 \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\fprovidesApis\x12?\n" +
	"\rconsumes_apis\x18\a \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\fconsumesApis\x129\n" +
	"\n" +
	"depends_on\x18\b \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\tdependsOn\"\xb9\x01\n" +
	"\fResourceSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12+\n" +
	"\x05owner\x18\x02 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x12-\n" +
	"\x06system\x18\x03 \x01(\v2\x15.swcat.catalog.v1.RefR\x06system\x129\n" +
	"\n" +
	"depends_on\x18\x04 \x03(\v2\x1a.swcat.catalog.v1.LabelRefR\tdependsOn\"\xf5\x01\n" +
	"\aApiSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\tlifecycle\x18\x02 \x01(\tR\tlifecycle\x12+\n" +
	"\x05owner\x18\x03 \x01(\v2\x15.swcat.catalog.v1.RefR\x05owner\x12-\n" +
	"\x06system\x18\x04 \x01(\v2\x15.swcat.catalog.v1.RefR\x06system\x12\x1e\n" +
	"\n" +
	"definition\x18\x05 \x01(\tR\n" +
	"definition\x12<\n" +
	"\bversions\x18\x06 \x03(\v2 .swcat.catalog.v1.ApiSpecVersionR\bversions\"c\n" +
	"\x0eApiSpecVersion\x123\n" +
	"\aversion\x18\x01 \x01(\v2\x19.swcat.catalog.v1.VersionR\aversion\x12\x1c\n" +
	"\tlifecycle\x18\x02 \x01(\tR\tlifecycle\"\xd9\x01\n" +
	"\tGroupSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12<\n" +
	"\aprofile\x18\x02 \x01(\v2\".swcat.catalog.v1.GroupSpecProfileR\aprofile\x12-\n" +
	"\x06parent\x18\x03 \x01(\v2\x15.swcat.catalog.v1.RefR\x06parent\x121\n" +
	"\bchildren\x18\x04 \x03(\v2\x15.swcat.catalog.v1.RefR\bchildren\x12\x18\n" +
	"\amembers\x18\x05 \x03(\tR\amembers\"e\n" +
	"\x10GroupSpecProfile\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x18\n" +
	"\apicture\x18\x03 \x01(\tR\apictureB8Z6github.com/dnswlt/swcat/internal/catalog/pb;catalog_pbb\x06proto3"

var (
	file_swcat_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_swcat_catalog_v1_catalog_proto_rawDescData []byte
)

func file_swcat_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_swcat_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_swcat_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swcat_catalog_v1_catalog_proto_rawDesc), len(file_swcat_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_swcat_catalog_v1_catalog_proto_rawDescData
}

var file_swcat_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_swcat_catalog_v1_catalog_proto_goTypes = []any{
	(*Metadata)(nil),         // 0: swcat.catalog.v1.Metadata
	(*Link)(nil),             // 1: swcat.catalog.v1.Link
	(*Ref)(nil),              // 2: swcat.catalog.v1.Ref
	(*LabelRef)(nil),         // 3: swcat.catalog.v1.LabelRef
	(*Version)(nil),          // 4: swcat.catalog.v1.Version
	(*Entity)(nil),           // 5: swcat.catalog.v1.Entity
	(*DomainSpec)(nil),       // 6: swcat.catalog.v1.DomainSpec
	(*SystemSpec)(nil),       // 7: swcat.catalog.v1.SystemSpec
	(*ComponentSpec)(nil),    // 8: swcat.catalog.v1.ComponentSpec
	(*ResourceSpec)(nil),     // 9: swcat.catalog.v1.ResourceSpec
	(*ApiSpec)(nil),          // 10: swcat.catalog.v1.ApiSpec
	(*ApiSpecVersion)(nil),   // 11: swcat.catalog.v1.ApiSpecVersion
	(*GroupSpec)(nil),        // 12: swcat.catalog.v1.GroupSpec
	(*GroupSpecProfile)(nil), // 13: swcat.catalog.v1.GroupSpecProfile
	nil,                      // 14: swcat.catalog.v1.Metadata.LabelsEntry
	nil,                      // 15: swcat.catalog.v1.Metadata.AnnotationsEntry
	nil,                      // 16: swcat.catalog.v1.LabelRef.AttrsEntry
}
var file_swcat_catalog_v1_catalog_proto_depIdxs = []int32{
	14, // 0: swcat.catalog.v1.Metadata.labels:type_name -> swcat.catalog.v1.Metadata.LabelsEntry
	15, // 1: swcat.catalog.v1.Metadata.annotations:type_name -> swcat.catalog.v1.Metadata.AnnotationsEntry
	1,  // 2: swcat.catalog.v1.Metadata.links:type_name -> swcat.catalog.v1.Link
	2,  // 3: swcat.catalog.v1.LabelRef.ref:type_name -> swcat.catalog.v1.Ref
	16, // 4: swcat.catalog.v1.LabelRef.attrs:type_name -> swcat.catalog.v1.LabelRef.AttrsEntry
	0,  // 5: swcat.catalog.v1.Entity.metadata:type_name -> swcat.catalog.v1.Metadata
	6,  // 6: swcat.catalog.v1.Entity.domain_spec:type_name -> swcat.catalog.v1.DomainSpec
	7,  // 7: swcat.catalog.v1.Entity.system_spec:type_name -> swcat.catalog.v1.SystemSpec
	8,  // 8: swcat.catalog.v1.Entity.component_spec:type_name -> swcat.catalog.v1.ComponentSpec
	9,  // 9: swcat.catalog.v1.Entity.resource_spec:type_name -> swcat.catalog.v1.ResourceSpec
	10, // 10: swcat.catalog.v1.Entity.api_spec:type_name -> swcat.catalog.v1.ApiSpec
	12, // 11: swcat.catalog.v1.Entity.group_spec:type_name -> swcat.catalog.v1.GroupSpec
	2,  // 12: swcat.catalog.v1.DomainSpec.owner:type_name -> swcat.catalog.v1.Ref
	2,  // 13: swcat.catalog.v1.DomainSpec.subdomain_of:type_name -> swcat.catalog.v1.Ref
	2,  // 14: swcat.catalog.v1.SystemSpec.owner:type_name -> swcat.catalog.v1.Ref
	2,  // 15: swcat.catalog.v1.SystemSpec.domain:type_name -> swcat.catalog.v1.Ref
	2,  // 16: swcat.catalog.v1.ComponentSpec.owner:type_name -> swcat.catalog.v1.Ref
	2,  // 17: swcat.catalog.v1.ComponentSpec.system:type_name -> swcat.catalog.v1.Ref
	2,  // 18: swcat.catalog.v1.ComponentSpec.subcomponent_of:type_name -> swcat.catalog.v1.Ref
	3,  // 19: swcat.catalog.v1.ComponentSpec.provides_apis:type_name -> swcat.catalog.v1.LabelRef
	3,  // 20: swcat.catalog.v1.ComponentSpec.consumes_apis:type_name -> swcat.catalog.v1.LabelRef
	3,  // 21: swcat.catalog.v1.ComponentSpec.depends_on:type_name -> swcat.catalog.v1.LabelRef
	2,  // 22: swcat.catalog.v1.ResourceSpec.owner:type_name -> swcat.catalog.v1.Ref
	2,  // 23: swcat.catalog.v1.ResourceSpec.system:type_name -> swcat.catalog.v1.Ref
	3,  // 24: swcat.catalog.v1.ResourceSpec.depends_on:type_name -> swcat.catalog.v1.LabelRef
	2,  // 25: swcat.catalog.v1.ApiSpec.owner:type_name -> swcat.catalog.v1.Ref
	2,  // 26: swcat.catalog.v1.ApiSpec.system:type_name -> swcat.catalog.v1.Ref
	11, // 27: swcat.catalog.v1.ApiSpec.versions:type_name -> swcat.catalog.v1.ApiSpecVersion
	4,  // 28: swcat.catalog.v1.ApiSpecVersion.version:type_name -> swcat.catalog.v1.Version
	13, // 29: swcat.catalog.v1.GroupSpec.profile:type_name -> swcat.catalog.v1.GroupSpecProfile
	2,  // 30: swcat.catalog.v1.GroupSpec.parent:type_name -> swcat.catalog.v1.Ref
	2,  // 31: swcat.catalog.v1.GroupSpec.children:type_name -> swcat.catalog.v1.Ref
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_swcat_catalog_v1_catalog_proto_init() }
func file_swcat_catalog_v1_catalog_proto_init() {
	if File_swcat_catalog_v1_catalog_proto != nil {
		return
	}
	file_swcat_catalog_v1_catalog_proto_msgTypes[5].OneofWrappers = []any{
		(*Entity_DomainSpec)(nil),
		(*Entity_SystemSpec)(nil),
		(*Entity_ComponentSpec)(nil),
		(*Entity_ResourceSpec)(nil),
		(*Entity_ApiSpec)(nil),
		(*Entity_GroupSpec)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swcat_catalog_v1_catalog_proto_rawDesc), len(file_swcat_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swcat_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_swcat_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_swcat_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_swcat_catalog_v1_catalog_proto = out.File
	file_swcat_catalog_v1_catalog_proto_goTypes = nil
	file_swcat_catalog_v1_catalog_proto_depIdxs = nil
}
