apiVersion: swcat/v1
kind: Domain
metadata:
  name: analytics
  description: Services for business analytics.
spec:
  owner: analytics-owner
---
apiVersion: swcat/v1
kind: Group
metadata:
  name: analytics-owner
  description: The owners of the analytics domain.
spec:
  type: team
  profile:
    displayName: Analytics Owner Group
    email: analytics@example.com
---
apiVersion: swcat/v1
kind: System
metadata:
  name: analytics-pipeline
  title: Analytics Pipeline
  description: The data pipeline for collecting and processing analytics events.
spec:
  owner: analytics-owner
  domain: analytics
---
apiVersion: swcat/v1
kind: API
metadata:
  name: analytics-events-api
  description: API for ingesting analytics events.
spec:
  type: kafka/csv
  lifecycle: production
  owner: analytics-owner
  system: analytics-pipeline
---
apiVersion: swcat/v1
kind: Resource
metadata:
  name: raw-events-storage
  description: Intermediate storage for raw analytics events.
spec:
  type: kafka
  owner: analytics-owner
  system: analytics-pipeline
---
apiVersion: swcat/v1
kind: Resource
metadata:
  name: processed-events-storage
  description: Queryable storage for processed analytics events.
spec:
  type: analytics-database
  owner: analytics-owner
  system: analytics-pipeline
---
apiVersion: swcat/v1
kind: Component
metadata:
  name: events-collector
  description: Collects analytics events and puts them into the raw events storage.
spec:
  type: service
  lifecycle: production
  owner: analytics-owner
  system: analytics-pipeline
  providesApis:
    - analytics-events-api
  dependsOn:
    - resource:raw-events-storage
---
apiVersion: swcat/v1
kind: Component
metadata:
  name: events-processor
  description: Processes raw events and stores them in the processed events storage.
spec:
  type: job
  lifecycle: production
  owner: analytics-owner
  system: analytics-pipeline
  dependsOn:
    - resource:raw-events-storage
    - resource:processed-events-storage
