name: Deploy Documentation

# Controls when the action will run.
# Triggers the workflow on push events for the main branch.
# Allows you to also run this workflow manually from the Actions tab.
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out your repository's code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Step 3: Install MkDocs and the Material theme
      - name: Install dependencies
        run: pip install mkdocs mkdocs-material

      # Step 4: Build and deploy the documentation
      # The `gh-deploy` command builds the site and pushes it to the `gh-pages` branch.
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force